In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('Fish.csv')

In [4]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [5]:
data.describe()

Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [6]:
x = data[['Length1','Length2','Length3','Height','Width']]

In [7]:
y = data['Weight']

In [8]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
reg.coef_

array([ 62.35521443,  -6.52675249, -29.02621861,  28.29735132,
        22.47330665])

In [10]:
reg.intercept_

-499.58695535694187

Calculating the R-squared

In [12]:
reg.score(x,y)

0.8852867046546206

In [13]:
x.shape

(159, 5)

### Formula for Adjusted R-Squared

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

n= number of observations
p= number of features/predictors

In [14]:
r2 = reg.score(x,y)

n = x.shape[0]

p = x.shape[1]


In [15]:
adjusted_r2 = 1- (1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.8815379041531376

## Feature Selection 

In [16]:
from sklearn.feature_selection import f_regression

In [17]:
f_regression(x,y)

(array([815.304476  , 848.49809728, 903.87828037, 173.30112409,
        576.28151245]),
 array([4.74961972e-64, 3.39511323e-65, 5.02319145e-67, 3.84234184e-27,
        2.03819464e-54]))

## first array<- F-statistics for each value
## second array<- p-values for each value

In [18]:
p_values = f_regression(x,y)[1]
p_values

array([4.74961972e-64, 3.39511323e-65, 5.02319145e-67, 3.84234184e-27,
       2.03819464e-54])

In [19]:
p_values.round(3)

array([0., 0., 0., 0., 0.])

# Creating a summary Table

In [23]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

Features
0  Length1
1  Length2
2  Length3
3   Height
4    Width

In [24]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [25]:
reg_summary

Features  Coefficients  p-values
0  Length1     62.355214       0.0
1  Length2     -6.526752       0.0
2  Length3    -29.026219       0.0
3   Height     28.297351       0.0
4    Width     22.473307       0.0

# Predicting with standardized coefficients