In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data =pd.read_csv('Fish.csv')
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [4]:
x= data[['Length1','Length2','Length3','Height','Width']]
y= data['Weight']

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler=StandardScaler()

In [7]:
scaler.fit(x) 
#Calculate the mean and Standard Deviation for the dataset

StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
x_scaled = scaler.transform(x)

In [9]:
x_scaled

array([[-3.05788578e-01, -2.82303007e-01, -1.06020232e-01,
         5.96578670e-01, -2.36528948e-01],
       [-2.25507242e-01, -1.98053663e-01, -2.33668373e-03,
         8.21260549e-01, -6.65789457e-02],
       [-2.35542409e-01, -1.79331587e-01, -1.09769794e-02,
         7.97341291e-01,  1.65793169e-01],
       [ 5.30159764e-03,  5.46943678e-02,  1.96390116e-01,
         8.79771455e-01,  2.26210031e-02],
       [ 2.53719316e-02,  5.46943678e-02,  2.39591594e-01,
         8.12834979e-01,  4.26371272e-01],
       [ 5.54774324e-02,  1.20221635e-01,  3.00073664e-01,
         1.08395111e+00,  3.03431249e-01],
       [ 5.54774324e-02,  1.20221635e-01,  2.82793073e-01,
         1.21901769e+00,  5.12357880e-01],
       [ 1.35758768e-01,  1.48304750e-01,  3.25994551e-01,
         8.65728838e-01,  1.62163285e-01],
       [ 1.35758768e-01,  1.48304750e-01,  3.34634847e-01,
         1.17815367e+00,  2.53683979e-01],
       [ 2.26075271e-01,  2.13832017e-01,  4.29678099e-01,
         1.23004114e+00

In [10]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
reg.coef_

array([ 621.36698553,  -69.72252823, -335.9401089 ,  120.90631145,
         37.76626234])

In [12]:
reg.intercept_

398.32641509433967

# Predicting with Standardized data
## Standardize the data to be predicted then run the regression

In [13]:
new_data = pd.DataFrame(data=[[20,21,22,10,3],[30,32,31,11,4]],columns=['Length1','Length2','Length3','Height','Width'])
new_data

Length1  Length2  Length3  Height  Width
0       20       21       22      10      3
1       30       32       31      11      4

In [14]:
reg.predict(new_data)

array([5293.17253876, 7875.10617731])

In [15]:
new_data_scaled = scaler.transform(new_data)

In [16]:
new_data_scaled

array([[-0.62691392, -0.69418869, -0.79724388,  0.24083236, -0.84349324],
       [ 0.37660278,  0.33552551, -0.01961728,  0.47487599, -0.24843021]])

In [17]:
reg.predict(new_data_scaled)

array([322.27215466, 663.56471203])